services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: celestin20
      MYSQL_DATABASE: vehicledb
      MYSQL_USER: celestin20
      MYSQL_PASSWORD: celestin20
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql+pymysql://celestin20:celestin20@db:3306/vehicledb

volumes:
  db_data:
